### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by lchanouha** [MPIB/hazel#10]
I user has an invalid session cookie, i can't connect anymore.

To reproduce on 1.1.0:

- login as user
- restart hazel: your are disconnected
- retry login: your credential are accepted but your are not connected

Manually deleting cooking solves the problem.

**Comment by Drakulix** [comment]
Should be fixed by f84be144340bb4e66017d38faef9530d06b322af in the new 1.1.0rc2. Feel free to reopen if you still have issues.
