### ISSUE TITLE
Correct way to add as Chocolatey source?

### ISSUE THREAD

**Issue by crsleeth** [MPIB/hazel#6]
When running choco source add what is the correct way to refer to Hazel?
For example:
`choco source add -s http://hazel-example.com:8080`?

**Comment by Drakulix** [comment]
I found `choco source add -s http://hazel-example.com:8080/api/v2` to be working more reliably.

For an explaination why, see this: http://chris.eldredge.io/blog/2013/02/25/fun-with-nuget-rest-api/
