### ISSUE TITLE
hazel_1.1.0rc1_amd64.deb - have some error

### ISSUE THREAD

**Issue by andryua** [MPIB/hazel#9]
Hi!
Cant install, because in hazel_1.1.0rc1_amd64.deb has error:
in INFO file in Depends not correct info
Please, correct its!
Thanks!

**Comment by octomike** [comment]
related to https://github.com/mmstick/cargo-deb/issues/25, I'll have a look and see if I am able to generate a working deb with cargo-deb

**Comment by octomike** [comment]
I fixed and replaced the RC1 deb in place.

But, I did not change the tag yet. @Drakulix will decide how to proceed with the pre-releases.

**Comment by andryua** [comment]
after install fixed version of deb package - hazle want start - said - cant read config file
but config file is in /etc

**Comment by andryua** [comment]
compiling version show error (same error - deb version)
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 98, message: "Address already in use" } })', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Drakulix** [comment]
Do you start hazel with the appropriate flags to tell it your config file location? (See [hazel.service](https://github.com/MPIB/hazel/blob/master/hazel.service) for example.)

Hazel expects the config file to be in the current directory if not passed via the matching command line argument ("-c").
`Address already in use` refers to the socket, which is by default on port 8080, you can override that with either another command line argument ("-p") or with the appropriate settings in your config file.

**Comment by andryua** [comment]
sorry, everything OK. I forget about postgresql databese...
